// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8XHEM11d0h1OGRfYjE_FFNBrQuFzeeY',
    appId: '1:935370940540:web:33f27ed17ff8becbdce9f9',
    messagingSenderId: '935370940540',
    projectId: 'fir-44666',
    authDomain: 'fir-44666.firebaseapp.com',
    storageBucket: 'fir-44666.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJXto33J6p2upf8j2Arx-Psf6ORzpbwAA',
    appId: '1:935370940540:android:5a9aba9344efb8e5dce9f9',
    messagingSenderId: '935370940540',
    projectId: 'fir-44666',
    storageBucket: 'fir-44666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSf0hKL4vl8Zvjka_6xHiYke59SrPmag',
    appId: '1:935370940540:ios:69c71da0e5d40de4dce9f9',
    messagingSenderId: '935370940540',
    projectId: 'fir-44666',
    storageBucket: 'fir-44666.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSf0hKL4vl8Zvjka_6xHiYke59SrPmag',
    appId: '1:935370940540:ios:69c71da0e5d40de4dce9f9',
    messagingSenderId: '935370940540',
    projectId: 'fir-44666',
    storageBucket: 'fir-44666.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-8XHEM11d0h1OGRfYjE_FFNBrQuFzeeY',
    appId: '1:935370940540:web:362b93cc227b05cbdce9f9',
    messagingSenderId: '935370940540',
    projectId: 'fir-44666',
    authDomain: 'fir-44666.firebaseapp.com',
    storageBucket: 'fir-44666.firebasestorage.app',
  );
}
