// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEQQl1vxovii4w0tC0S7RozykfDDEfo0',
    appId: '1:376712370421:web:a00522deb38f3ec5c14dbc',
    messagingSenderId: '376712370421',
    projectId: 'hackathon-fac37',
    authDomain: 'hackathon-fac37.firebaseapp.com',
    storageBucket: 'hackathon-fac37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKYX205AkIFb4QkZSY-_ZCKHMXPCNrMU',
    appId: '1:376712370421:android:6972c12b62a440c8c14dbc',
    messagingSenderId: '376712370421',
    projectId: 'hackathon-fac37',
    storageBucket: 'hackathon-fac37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBx8g5sFngOtm3NFte5xUnblRSHvhcDX4',
    appId: '1:376712370421:ios:64e5a37512d48abac14dbc',
    messagingSenderId: '376712370421',
    projectId: 'hackathon-fac37',
    storageBucket: 'hackathon-fac37.firebasestorage.app',
    iosBundleId: 'com.example.hackathonApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBx8g5sFngOtm3NFte5xUnblRSHvhcDX4',
    appId: '1:376712370421:ios:64e5a37512d48abac14dbc',
    messagingSenderId: '376712370421',
    projectId: 'hackathon-fac37',
    storageBucket: 'hackathon-fac37.firebasestorage.app',
    iosBundleId: 'com.example.hackathonApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnEQQl1vxovii4w0tC0S7RozykfDDEfo0',
    appId: '1:376712370421:web:528f8bad89db6405c14dbc',
    messagingSenderId: '376712370421',
    projectId: 'hackathon-fac37',
    authDomain: 'hackathon-fac37.firebaseapp.com',
    storageBucket: 'hackathon-fac37.firebasestorage.app',
  );
}
